### ISSUE TITLE
SEF Issue

### ISSUE THREAD

**Issue by ghost** [glosswordteam/Glossword#1]
Hi,

I'm using Glossword 1.9.3.1 for Joomla! 1.5.23 and I have a SEF issue after I activate SEF from Artio JoomSEF component.
I tried all handling types for this component from JoomSEF Extension management and no result.
You can see here the problem: http://www.manigordo.ro/dictionar/default
And that's not all... if I turn On mod_apache the desing of the page is changing...

What should i do?
Thx.

**Comment by glosswordteam** [comment]
Try to enable Joomla's setting "Adds Suffix to URL" (Site -> Global configuration -> SEO Settings)

If it would not help, I need a temporary account to Joomla with permission to change files.

**Comment by ghost** [comment]
I tried what you've said and no result. Even after I clean cache and purge urls form Artio JoomSEF.
I'll sent you a message with an account.

**Comment by ghost** [comment]
I just sent you a PM with the account.

**Comment by glosswordteam** [comment]
Received. Will check it asap.

**Comment by glosswordteam** [comment]
Well, I've found that I need to write additional "SEF extension" for JoomSEF to make it work right. It takes time.

**Comment by ghost** [comment]
I knew that it needs an additional sef ext. for JoomSEF but I believed that it will work without one, just with core sef, and I tried to make one following the com_example from JoomSEF, but I'm a newbie in php so no result for now.
So.. can you help me? And if you do, then how much time it takes?
Thanks.
